pipeline {
    agent any
	tools { 
        maven 'M2' 
        jdk 'Java8' 
    }
    stages {
        stage('Build') {
            steps {
                //sh 'mvn -B -DskipTests clean package'
		    sh 'mvn clean package sonar:sonar' 
            }
        }
        
    }
}
