pipeline {

    agent any 
        tools {
            maven 'MAVEN_HOME'
            jdk 'JDK-12'
        }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}
